"""add a users table

Revision ID: 199f550bbd83
Revises: 2b1f85731c00
Create Date: 2026-04-11 15:56:14.863795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '199f550bbd83'
down_revision = '2b1f85731c00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
